openapi: 3.0.3
info:
  title: Pear Phones API
  version: 1.0.0
  description: |
    Public endpoints used for communication to Pear Phones Company

servers:
  - url: https://pear-company-api.projects.bbdgrad.com/public-api

components:
  schemas:
    Order:
      type: object
      required:
        - account_number
        - items
      properties:
        account_number:
          type: string
        items:
          type: array
          items:
            type: object
            required: 
              - model
              - quantity
            properties:
              model: 
                type: string
                enum: [ePhone, ePhone plus, ePhone pro max]
              quantity: 
                type: number

    Stock:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            required: 
              - phoneId
              - name
              - quantity
              - price
            properties:
              phoneId: 
                type: number
              name:
                type: string
              quantity: 
                type: number
              price:
                type: number
                format: float

    MachineFailure:
      type: object
      required:
        - machineName
        - failureQuantity
        - simulationDate
        - simulationTime
      properties:
        machineName:
          type: string
          description: Name of the phone model whose machines failed (matches phones.name)
        failureQuantity:
          type: integer
          minimum: 0
          description: Number of machines to retire
        simulationDate:
          type: string
          format: date
          description: Date of the failure event (YYYY-MM-DD)
        simulationTime:
          type: string
          pattern: '14:30:45'
          description: Time of the failure event (HH:MM:SS)
    
    OrderResponse:
      type: object
      required:
        - orderId
        - price
      properties:
        order_id:
          type: number
          description: Reference number to use for payment
        price:
          type: number
          format: float
          description: Total price of the order
        accountNumber:
          type: string
          example: "123456789012"
          description: Bank account number for phones

    DeliveryConfirmation:
      type: object
      required:
        - delivery_reference
      properties:
        delivery_reference:
          type: number
          description: Delivery reference number
    
    PickupRequest:
      type: object
      required:
       - type
       - id
       - quantity
      properties:
        type:
          type: string
          enum: [PICKUP]
          description: Type of logistics request
        id:
          type: string
          description: Delivery reference for consumer logistics
        quantity:
          type: number
          description: Quantity being picked up
    
    DeliveryRequest:
      type: object
      required:
        - type
        - id
        - items
      properties:
        type:
          type: string
          enum: [DELIVERY]
          description: Type of logistics request
        id:
          type: number
          description: Delivery reference for bulk logistics
        items:
          type: array
          items:
            type: object
            properties:
              itemName:
                type: string
              quantity:
                type: number
              measurementType:
                type: string
                enum: [KG, UNIT]
                description: "UNIT/KG"
          description: Array of items being delivered


paths:
  /simulations:
    post:
      summary: Start a new simulation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - epochStartTime
              properties:
                epochStartTime:
                  type: string
                  description: Unix epoch time of simulation start
      responses:
        '200':
          description: Simulation started
          
  /machines/failure:
    post:
      summary: Break a machine random event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MachineFailure'
      responses:
        '200':
          description: Machine failure is recorded
        '400':
          description: Invalid request body

  /stock:
    get:
      summary: Get current phone stock
      responses:
        '200':
          description: List of phones with stock availability and price per phone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'
                      
  /orders:
    post:
      summary: Make an order for phones
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Order placed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid order data

  /logistics:
    post:
      summary: Confirm delivery or pickup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/PickupRequest'
                - $ref: '#/components/schemas/DeliveryRequest'
                
      responses:
        '200':
          description: Delivery request accepted
        '400':
          description: Invalid delivery data
          
  /logistics/notification:
    post:
      summary: Notify an order has been delivered
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - delivery_reference
              properties:
                delivery_reference: 
                  type: string
      responses:
        '200':
          description: Accepted
        '400':
          description: Invalid delivery reference