openapi: 3.0.1
info:
  title: RetailBank
  version: '1.0'
paths:
  /accounts:
    post:
      tags:
        - AccountEndpoints
      summary: Create Transactional Account
      description: "Create a transactional account. Transactional \r\naccounts have an account number consisting of 12 \r\ndigits starting with `1000`."
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionAccountRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccountResponse'
    get:
      tags:
        - AccountEndpoints
      summary: Get All Accounts
      description: "Lookup all accounts by account type in order of newest to oldest.\r\n`next` will contain the URL for the next batch of\r\naccounts, or it will be `null` if no accounts were returned.\r\n\r\nNotable accounts:\r\n- Retail Bank Main Account: `1000`\r\n- Owners Equity Account: `1001`\r\n- Interest Income Account: `1002`\r\n- Loan Control Account: `1003`\r\n- Bad Debts Account: `1004`\r\n- Commercial Bank: `2000`"
      parameters:
        - name: accountType
          in: query
          schema:
            $ref: '#/components/schemas/LedgerAccountType'
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
            default: 25
        - name: timestampMax
          in: query
          schema:
            type: integer
            format: int64
            default: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountDto'
  '/accounts/{id}':
    get:
      tags:
        - AccountEndpoints
      summary: Get An Account
      description: "Get information about any account.\r\n\r\nNotable accounts:\r\n- Retail Bank Main Account: `1000`\r\n- Owners Equity Account: `1001`\r\n- Interest Income Account: `1002`\r\n- Loan Control Account: `1003`\r\n- Bad Debts Account: `1004`\r\n- Commercial Bank: `2000`"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDto'
        '404':
          description: Not Found
  '/accounts/{id}/transfers':
    get:
      tags:
        - AccountEndpoints
      summary: Get An Account's Transfers
      description: "Get all transfers credited/debited to an account,\r\nreturns empty array if account does not exist.\r\n`next` will contain the URL for the next batch of\r\ntranfers, or it will be `null` if no transfers were returned."
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
            default: 25
        - name: timestampMax
          in: query
          schema:
            type: integer
            format: int64
            default: 0
        - name: side
          in: query
          schema:
            $ref: '#/components/schemas/TransferSide'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferDtoCursorPagination'
  '/accounts/{id}/loans':
    get:
      tags:
        - AccountEndpoints
      summary: Get An Account's Loans
      description: "Get all loans to this account, returns empty array if\r\naccount does not exist."
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountDto'
  /loans:
    post:
      tags:
        - LoanEndpoints
      summary: Issue a Loan to a Transactional Account
      description: "Create a loan account of the requested amount,\r\nand deposit the principal amount into the debtor's\r\naccount. Each month, interest will be added to the\r\nto the loan account, and an installment will be\r\ntranferred from the debtor's account to the loan\r\naccount. The loan will pay itself off after 60 months."
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLoanAccountRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccountResponse'
  /report:
    get:
      tags:
        - ReportingEndpoints
      responses:
        '200':
          description: OK
  /simulation:
    post:
      tags:
        - SimulationEndpoints
      summary: Start Simulation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartSimulationRequest'
        required: true
      responses:
        '204':
          description: No Content
    delete:
      tags:
        - SimulationEndpoints
      summary: Reset Simulation
      responses:
        '204':
          description: No Content
  /transfers:
    post:
      tags:
        - TransferEndpoints
      summary: Transfer
      description: "Transfer money between accounts. Debiting account\r\n`from` and crediting account `to`. This can be used \r\nfor transfers between retail bank accounts, and \r\nfor transfers to the commercial bank. Retail bank \r\naccount numbers start with `1000`, while commercial \r\nbank account numbers start with `2000`."
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransferRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTransferResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    get:
      tags:
        - TransferEndpoints
      summary: Get All Transfers
      description: "Get all transfers. `next` will contain the URL for\r\nthe next batch of tranfers, or it will be `null` if\r\nno transfers were returned."
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
            default: 25
        - name: timestampMax
          in: query
          schema:
            type: integer
            format: int64
            default: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferDtoCursorPagination'
  '/transfers/{id}':
    get:
      tags:
        - TransferEndpoints
      summary: Get A Transfer
      description: Get information about a transfer.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferDto'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    AccountDto:
      type: object
      properties:
        id:
          type: string
          nullable: true
        accountType:
          $ref: '#/components/schemas/LedgerAccountType'
        debitsPending:
          type: integer
          format: int128
        debitsPosted:
          type: integer
          format: int128
        creditsPending:
          type: integer
          format: int128
        creditsPosted:
          type: integer
          format: int128
        balancePending:
          type: integer
          format: int128
        balancePosted:
          type: integer
          format: int128
        closed:
          type: boolean
        createdAt:
          type: integer
          format: int64
      additionalProperties: false
    CreateAccountResponse:
      type: object
      properties:
        accountId:
          type: string
          nullable: true
      additionalProperties: false
    CreateLoanAccountRequest:
      type: object
      properties:
        loanAmountCents:
          type: integer
          format: int64
        debtorAccountId:
          type: string
          nullable: true
      additionalProperties: false
    CreateTransactionAccountRequest:
      type: object
      properties:
        salaryCents:
          type: integer
          format: int64
      additionalProperties: false
    CreateTransferRequest:
      type: object
      properties:
        from:
          type: string
          nullable: true
        to:
          type: string
          nullable: true
        amountCents:
          type: integer
          format: int128
        reference:
          type: integer
          format: int64
          nullable: true
      additionalProperties: false
    CreateTransferResponse:
      type: object
      properties:
        transferId:
          type: string
          nullable: true
      additionalProperties: false
    LedgerAccountType:
      enum:
        - Internal
        - Transactional
        - Loan
      type: string
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
    StartSimulationRequest:
      type: object
      properties:
        unixEpochStartTime:
          type: integer
          format: int64
      additionalProperties: false
    TransferDto:
      type: object
      properties:
        transferId:
          type: string
          nullable: true
        transferType:
          $ref: '#/components/schemas/TransferType'
        debitAccountId:
          type: string
          nullable: true
        creditAccountId:
          type: string
          nullable: true
        amount:
          type: integer
          format: int128
        parentId:
          type: string
          nullable: true
        timestamp:
          type: integer
          format: int64
        reference:
          type: integer
          format: int64
          nullable: true
      additionalProperties: false
    TransferDtoCursorPagination:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TransferDto'
          nullable: true
        next:
          type: string
          nullable: true
      additionalProperties: false
    TransferSide:
      enum:
        - Debit
        - Credit
      type: string
    TransferType:
      enum:
        - Transfer
        - StartTransfer
        - CompleteTransfer
        - CancelTransfer
        - BalanceDebit
        - BalanceCredit
        - CloseDebit
        - CloseCredit
      type: string
