openapi: 3.0.3
info:
  title: Electronics Supplier API
  version: 1.0.0
  description: API for getting stock, prices, and making orders for our Electronics.

servers:
  - url: http://localhost:8080

tags:
  - name: Electronics
    description: Get details of electronics
  - name: Orders
    description: Order electronics and get the details of the order

paths:
  /electronics:
    get:
      tags: [Electronics]
      summary: Get the details of our electronic units
      description: Get how many units we have and how much per unit
      responses:
        200:
          description: Details of our electronics
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ElectronicsDetails'

  /orders:
    post:
      tags: [Orders]
      summary: Create a new electronics order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElectronicsOrderRequest'
      responses:
        201:
          description: Electronics order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectronicsOrderResponse'
              

  /orders/{orderId}:
    get:
      tags: [Orders]
      summary: Get an electronics order
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Electronics order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectronicsOrder'


components:
  schemas:
    ElectronicsOrderRequest:
      type: object
      properties:
        quantity:
          type: integer
          example: 1000
    ElectronicsOrderResponse:
      type: object
      properties:
        orderId:
          type: integer
          example: 5432
          description: The order ID of your order
        quantity:
          type: integer
          example: 1000
          description: How many units of electronics you ordered
        amountDue:
          type: number
          example: 5000
          description: How much money you owe us
        bankNumber:
          type: string
          example: "123456123456"
          description: "Our bank account number for you to pay us"
    ElectronicsOrder:
      type: object
      properties:
        orderId:
          type: integer
          example: 5432
        status:
          type: string
          example: "InTransit"
        orderedAt:
          type: number
          example: 27
        quantity:
          type: integer
          example: 1000
        remainingAmount:
          type: number
          example: 500
    ElectronicsDetails:
      type: object
      properties:
        availableStock:
          type: integer
          example: 2000
        pricePerUnit:
          type: number
          example: 5.0