openapi: 3.0.3
info:
  title: Electronics Supplier API
  version: 1.0.0
  description: API for getting stock, prices, and making orders for our Electronics.

servers:
  - url: http://electronics-supplier-api.projects.bbdgrad.com

tags:
  - name: Electronics
    description: Get details of electronics
  - name: Orders
    description: Order electronics and get the details of the order
  - name: Logistics
    description: For Bulk Logistics integration

paths:
  /electronics:
    get:
      tags: [Electronics]
      summary: Get the details of our electronic units
      description: Get how many units we have and how much per unit
      responses:
        200:
          description: Details of our electronics
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ElectronicsDetails'

  /orders:
    post:
      tags: [Orders]
      summary: Create a new electronics order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElectronicsOrderRequest'
      responses:
        201:
          description: Electronics order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectronicsOrderResponse'
              

  /orders/{orderId}:
    get:
      tags: [Orders]
      summary: Get an electronics order
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Electronics order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectronicsOrder'
  
  /logistics:
    post:
      tags: [Logistics]
      summary: Handle logistics requests for material delivery or electronics pickup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Order ID (for delivery) or pickup request ID (for pickup)
                  example: "123"
                type:
                  type: string
                  description: Type of logistics operation ("PICKUP" or "DELIVERY")
                  enum: ["PICKUP", "DELIVERY"]
                  example: "DELIVERY"
                quantity:
                  type: integer
                  description: Number of items to deliver or pick up
                  example: 10
              required:
                - id
                - type
                - quantity
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  remaining:
                    type: integer
        '400':
          description: Bad request (validation or business logic error)
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not found (order not found)
          content:
            application/json:
              schema:
                type: string


components:
  schemas:
    ElectronicsOrderRequest:
      type: object
      properties:
        quantity:
          type: integer
          example: 1000
    ElectronicsOrderResponse:
      type: object
      properties:
        orderId:
          type: integer
          example: 5432
          description: The order ID of your order
        quantity:
          type: integer
          example: 1000
          description: How many units of electronics you ordered
        amountDue:
          type: number
          example: 5000
          description: How much money you owe us
        bankNumber:
          type: string
          example: "123456123456"
          description: "Our bank account number for you to pay us"
    ElectronicsOrder:
      type: object
      properties:
        orderId:
          type: integer
          example: 5432
        status:
          type: string
          example: "InTransit"
        orderedAt:
          type: number
          example: 27
        quantity:
          type: integer
          example: 1000
        remainingAmount:
          type: number
          example: 500
    ElectronicsDetails:
      type: object
      properties:
        availableStock:
          type: integer
          example: 2000
        pricePerUnit:
          type: number
          example: 5.0