openapi: 3.0.0
info:
  title: Case Supplier API
  version: 1.0.0
tags:
  - name: Case
    description: Case product and inventory

paths:
  /cases:
    get:
      tags:
        - Case
      summary: Get cases in stock and current price per unit
      description: Returns available case inventory and pricing
      responses:
        200:
          description: Available cases and price per unit
          content:
            application/json:
              schema:
                type: object
                properties:
                  available_units:
                    type: integer
                    example: 2456
                  price_per_unit:
                    type: number
                    example: 100.0